#pragma config(Sensor, in1,    lift_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    claw_potentiometer, sensorPotentiometer)
#pragma config(Motor,  port1,           D_BL,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           D_TL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L_BL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L_TL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           L_R,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           R_L,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           R_TR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R_BR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           D_TR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          D_BR,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void setDrive(int L, int R){
	motor[D_TL] = L;
	motor[D_BL] = L;
	motor[D_TR] = R;
	motor[D_BR] = R;
}

void setLift(int power){
	motor[L_TL] = power;
	motor[L_BL] = power;
	motor[L_R] = -power;

	motor[R_TR] = -power;
	motor[R_BR] = -power;
	motor[R_L] = power;
}

/*************** AUTON DRIVE ***************/

typedef struct
{
	int t;
	int l;
	int r;
} driveInfo;

const int numDriveInfos = 2;
struct driveInfo driveAuton[numDriveInfos] =
{
		{ 500, 127, 127 },
		{ 500, 127, 127 }
};

task handleAutonDrive(){
	for( int i = 0; i < numDriveInfos; i++) {
		setDrive(driveAuton[i].l, driveAuton[i].r);
		wait1Msec(driveAuton[i].t);
	}
	stopTask(handleAutonDrive);
}

/*************** AUTON LIFT ***************/

typedef struct
{
	int t;
	int p;
} liftInfo;

struct liftInfo* liftWait(int time) {
	liftInfo info = (liftInfo) { time, 0 };
}

const int numLiftInfos = 2;
struct liftInfo liftAuton[numLiftInfos] =
{
		{ 500 , 127 },
		{ 500 , 127 }
};

task handleAutonLift(){
	for( int i = 0; i < numLiftInfos; i++) {
		setLift(liftAuton[i].p);
		wait1Msec(liftAuton[i].t);
	}
	stopTask(handleAutonLift);
}

/******************** AUTON ****************/

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

void mimicAuton() {
	startTask(handleAutonDrive);
	startTask(handleAutonLift);

	// define vars such that this function only takes as much time as it needs to
	int largerTime = 0;
	int driveTime = 0;
	int liftTime = 0;

	// find which task takes more time
	for (int i = 0; i < numDriveInfos; i++) {driveTime += driveAuton[i].t; 	}
	for (int i = 0; i < numLiftInfos; i++) {liftTime += liftAuton[i].t; 	}
	if (liftTime > driveTime) largerTime = liftTime;
	else largerTime = driveTime;

	// wait for min time needed
	wait1Msec(driveTime);
}

task autonomous()
{
	mimicAuton();
}

/**************** USER ****************/

task usercontrol()
{
  while (true)
  {
  	if(vexRT[Btn7D]) {
  		mimicAuton();
  	}
  	setLift(127 * (-vexRT[Btn6U] + vexRT[Btn6D]));
  	setDrive(127 * vexRT[Ch4], 127 * vexRT[Ch2]);
  }
}
