#pragma config(Sensor, in1,    lift_potentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    claw_potentiometer, sensorPotentiometer)
#pragma config(Motor,  port1,           D_BL,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           D_TL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L_BL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L_TL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           L_R,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           R_L,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           R_TR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R_BR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           D_TR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          D_BR,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void setDrive(int L, int R){
	motor[D_TL] = L;
	motor[D_BL] = L;
	motor[D_TR] = R;
	motor[D_BR] = R;
}

void setLift(int power){
	motor[L_TL] = power;
	motor[L_BL] = power;
	motor[L_R] = -power;

	motor[R_TR] = -power;
	motor[R_BR] = -power;
	motor[R_L] = power;
}

/*************** AUTON ***************/


/*
int autonDriveInfo[4][3] =
{
	{ 1000, 127, 127 },
	{ 1000, 127, 127 },
	{ 1000, 127, 127 },
	{ 1000, 127, 127 }
};
task autonDrive() {
	int i;
	for ( i = 0; i < sizeof autonDriveInfo / sizeof autonDriveInfo[0] ; i = i + 1 ) {
		setDrive(autonDriveInfo[1], autonDriveInfo[2]);
		wait1Msec(autonDriveInfo[0]);
	}
}
*/

typedef struct
{
	int t;
	int l;
	int r;
} driveInfo;

const int numDriveInfos = 2;
struct driveInfo driveAuton[2] =
{
		{500, 127, 127 },
		{500, 127, 127 }
};
/*
{
		(driveInfo) { .t = 500,  .l = 127, .r = 127 },
		(driveInfo) { .t = 500,  .l = 0,   .r = 127 }
};
*/
/*
struct driveInfo func(int time, int left, int right) {
	struct driveInfo info;
	info.t = time;
	info.l = left;
	info.r = right;
	return info;

}
*/

task handleAutonDrive(){
	for( int i = 0; i < numDriveInfos; i++) {
		setDrive(driveAuton[i].l, driveAuton[i].r);
		wait1Msec(driveAuton[i].t);
	}
}


void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task timeTracker(){

}

task autonomous()
{

}

/**************** USER ****************/

task usercontrol()
{
  while (true)
  {
  	setLift(127 * (-vexRT[Btn6U] + vexRT[Btn6D]));
  	setDrive(127 * vexRT[Ch4], 127 * vexRT[Ch2]);
  }
}
